embedding_model:
  name: "BAAI/bge-m3"
  device: "cuda"

preprocessor:
  min_description_quantile: 0.05
  similarity_threshold: 0.95
  deduplicate_embedding_model: 'sentence-transformers/all-MiniLM-L6-v2'

clustering:
  n_clusters: 20
  random_state: 42
  batch_size: 1024
  max_features: 2000

generation_model:
  model_name: "gemini-3-flash-preview"

dataset_generation:
  train:
    positive_output_path: "scripts_output/generated/positive.jsonl"
    negative_output_path: "scripts_output/generated/hard_negative.jsonl"
    final_dataset_path: "scripts_output/training_dataset.csv"
    k_hard_negs: 1
    k_easy_negs: 3

  test:
    positive_output_path: "scripts_output/generated/positive_test.jsonl"
    negative_output_path: "scripts_output/generated/hard_negative_test.jsonl"
    final_dataset_path: "scripts_output/test_dataset.csv"
    k_hard_negs: 5
    k_easy_negs: 9

  qa:
    positive_output_path: "scripts_output/generated/positive_qa.jsonl"
    negative_output_path: "scripts_output/generated/hard_negative_qa.jsonl"
    final_dataset_path: "scripts_output/quality_test_dataset.csv"
    k_hard_negs: 1
    k_easy_negs: 18

data_split:
  train_ratio: 0.8
