embedding_model:
  name: "BAAI/bge-m3"
  device: "cuda"

preprocessor:
  min_description_quantile: 0.05
  similarity_threshold: 0.95

clustering:
  n_clusters: 20
  random_state: 42
  batch_size: 1024
  max_features: 2000